name: Build and Push to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - aws-deployment

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: learningprojects/document-version-update-events-ryan
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::124990256579:role/GitHubActionsEcrPushRole
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Docker image for ECR
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG 124990256579.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push 124990256579.dkr.ecr.eu-west-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
